### ISSUE TITLE
Increase maximum episodes number in feed manager

### ISSUE THREAD

**Issue by diveflo** [Yetangitu/Spodcast#11]
Hi,

would it be possible to allow a higher number than 5 episodes to sync (max episodes) in the feed manager?
I have a podcast that somehow have their episodes in the wrong order so the automatic sync isn't working for this one.

Thanks!

**Comment by Yetangitu** [comment]
Can you send a link to the feed? This sounds strange, maybe the problem can be solved so that automatic sync works there as well.

**Comment by diveflo** [comment]
https://open.spotify.com/show/09rIWfzXpDbWQf2paN0g6u

**Comment by Yetangitu** [comment]
This problem should be fixed in the latest release [(v0.4.9)](https://github.com/Yetangitu/Spodcast/releases/tag/v0.4.9) which now explicitly reverse-sorts episodes on release date. If you installed through _pip_ you can upgrade using `pip install -U spodcast`.

**Comment by diveflo** [comment]
awesome - it works now! thank u so much <3
