### ISSUE TITLE
Generate HTML Content Independent of Login

### ISSUE THREAD

**Issue by heywoodlh** [Yetangitu/Spodcast#17]
For the `docker-compose.yml` and corresponding images, it would be nice if the `--prepare-feed` flag could generate the HTML for the base application (i.e. without any podcasts downloaded yet). 

With the current state of the `docker-compose.yml` file I am about to PR, if a user attempts to visit the application the first time they run the `docker-compose.yml` they will be met with a 404 error (because Spodcast has not run yet). By setting `CRON_SCHEDULE` to something like `* * * * *` a user can workaround that -- but it'd be nice as an end-user to know the application is actually running whether or not any podcasts have been downloaded yet.

**Comment by Yetangitu** [comment]
I'll look into these issues one of these days, was busy doing other (more important) things.

**Comment by heywoodlh** [comment]
Hey no worries! Thanks for looking into it whenever you get around to it.
