### ISSUE TITLE
Where is the run.sh file coming from?

### ISSUE THREAD

**Issue by vittoriom** [Yetangitu/Spodcast#31]
When I pull the public image from Docker Hub and I run it, I see there is a run.sh file that actually reads the env variables passed to the docker run command. I'd like to add one more variable to support dynamic folder name, but I can't find any spec or code reference where the run.sh file is generated or copied to the Docker image. 

Any pointers?

Thanks!

**Comment by chessmango** [comment]
Looks like it's all built here: https://github.com/heywoodlh/Spodcast. You could submit a PR there, I'd imagine. Alternatively fork and build yourself I suppose

**Comment by vittoriom** [comment]
thank you, I didn't realize I was looking at the wrong fork! I actually ended up doing my own fork and creating my own run.sh. Resolving
