### ISSUE TITLE
Zombie 'Exited' containers

### ISSUE THREAD

**Issue by jame25** [Yetangitu/Spodcast#32]
Description:
When I run the following command, an 'exited' container is created. These 'exited' containers soon add up to 100s of zombie containers as I run this command for various podcasts every 24hrs. Any advice would be greatly appreciated.

`docker run -v /home/plex/Docker/spodcast_data:/data heywoodlh/spodcast -c /data/spodcast.json --skip-existing yes --rss-feed yes --log-level info --max-episodes 10 'open.spotify.com/show/3UhsI7s4bkH1FcMZI5u9iD'`

<img width="1069" alt="Capture" src="https://user-images.githubusercontent.com/13631646/218325122-5cd6f619-c806-4135-9b25-1d981b5e112d.PNG">

**Comment by lucajet** [comment]
run those with docker run --rm

(it will get rid upon exit)

**Comment by lucajet** [comment]
you helped me too because i was trying today and i was missing --rss-feed yes
